version: '3'
services:
  app:
    build: .
    ports:
      - "8081:8080" # Подставляем внешний порт
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    restart: unless-stopped # Автоматический перезапуск при сбое
  db:
    image: postgres:17.0 # Указание версии PostgreSQL
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    restart: unless-stopped # Автоматический перезапуск при сбое
